server:
  tomcat:
    max-swallow-size: -1 # Permitir que el servidor "trague" la solicitud aunque exceda el límite

spring:
  servlet:
    multipart:
      max-file-size: 500MB # Tamaño máximo de un solo archivo (ejemplo: 50MB)
      max-request-size: 500MB # Tamaño máximo total de la solicitud (archivos + datos)
      file-size-threshold: 10MB # Umbral para escribir a disco en lugar de RAM
  application:
    name: api
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/clip
    username: clip_user
    password: clip_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #validate #update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      flywaydb: DEBUG
